# Generated by Django 3.1.7 on 2021-03-15 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import review_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('isbn_no', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('cover_photo', models.ImageField(blank=True, default='', null=True, upload_to=review_system.models.image_upload_filter)),
                ('isArt', models.BooleanField(default=False)),
                ('isAction', models.BooleanField(default=False)),
                ('isAdventure', models.BooleanField(default=False)),
                ('isBiography', models.BooleanField(default=False)),
                ('isEncyclopedia', models.BooleanField(default=False)),
                ('isComedy', models.BooleanField(default=False)),
                ('isRomance', models.BooleanField(default=False)),
                ('isHorror', models.BooleanField(default=False)),
                ('isThriller', models.BooleanField(default=False)),
                ('isTravel', models.BooleanField(default=False)),
                ('isRecipe', models.BooleanField(default=False)),
                ('isYoungAdult', models.BooleanField(default=False)),
                ('isSatire', models.BooleanField(default=False)),
                ('isCrime', models.BooleanField(default=False)),
                ('isReligious', models.BooleanField(default=False)),
                ('isSports', models.BooleanField(default=False)),
                ('isSciFi', models.BooleanField(default=False)),
                ('isFantasy', models.BooleanField(default=False)),
                ('isDrama', models.BooleanField(default=False)),
                ('isChildren', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_system.book')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review_system.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
