# Generated by Django 3.1.7 on 2021-03-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn_no',
        ),
    ]
