# Generated by Django 3.1.7 on 2021-03-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0002_remove_book_isbn_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='isAction',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isAdventure',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isArt',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isBiography',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isChildren',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isComedy',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isCrime',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isDrama',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isEncyclopedia',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isFantasy',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isHorror',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isRecipe',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isReligious',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isRomance',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isSatire',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isSciFi',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isSports',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isThriller',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isTravel',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isYoungAdult',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='review_system.Tag'),
        ),
    ]
